### ISSUE TITLE
Which section should I be focusing my edits on?

### ISSUE THREAD

**Issue by taddallas** [PoisotLab/ms_mangal_synthesis#2]
I was invited to join this project, but I'm unsure what specific areas I should be focused on. I'm happy to go through and do general tweaks and such, but I don't want to get in the way or actively detract from the manuscript development and/or flow.

**Comment by tpoisot** [comment]
Can you go over the MS and give general feedback on the message? Are there things we've missed? You can use the md file or just the online version annotations: https://poisotlab.github.io/ms_mangal_synthesis/index.html

**Comment by taddallas** [comment]
I branched it up (`tadEdits`) and added my comments. I also changed some of the formatting and a couple of words throughout. I didn't want to mess too much with existing manuscript flow though. Hopefully I didn't mess everything up.
